### ISSUE TITLE
Suggestion for addition of in-game content

### ISSUE THREAD

**Issue by ghost** [nilesr/United4#2]
I think it would be beneficial to include the danger/u/ threads, Augmented Eye articles, and Kira Miki blog posts from the original game. If possible, this content could be available offline like the music player and Nanocamo App.

**Comment by purifetchi** [comment]
the thing is, danger/u/, augmented eye and kira miki's blog are an entity by itself.
they are a website and the content is all userbased, there is no possibility of making it offline. even if we'd make threads like these from the game, they would still be drowned by other posts the userbase made.
