### ISSUE TITLE
massive delay when inputting in a new Awoo endpoint

### ISSUE THREAD

**Issue by purifetchi** [nilesr/United4#5]
maybe it's just my OCD kicking in, but the *other* textbox in the awoo endpoint change submenu works really fucking slow
there is like a second delay between keypresses

**Comment by nilesr** [comment]
That's because it literally saves it out to disk every time you change it because I was lazy. I'll fix it after finals

**Comment by purifetchi** [comment]
surely

**Comment by nilesr** [comment]
With the rewritten properties system, it no longer writes to disk, but requests it to be written out asynchronously, so this should no longer be a problem.
